# netlify.toml
[build]
  command = "npm install && npm run build --prefix frontend"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

  # Força o esbuild a não externalizar *nada* por padrão, exceto as dependências padrão do Node.js.
  # Isso faz com que ele tente empacotar TUDO do node_modules.
  external_node_modules = [] 

  # Certifique-se de que o caminho para o node_modules da função é claro para o bundler.
  # Se você moveu o package.json da função para a raiz, o postinstall já cuida da instalação.
  # Esta linha é uma redundância para garantir que ele encontre os arquivos.
  included_files = ["netlify/functions/node_modules/**"]