# netlify.toml
[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend" # Instala e constrói o frontend
  publish = "frontend/dist"               # Onde o Vite gera os arquivos de build do React

[functions]
  directory = "netlify/functions"         # Onde suas funções Netlify estão localizadas
  node_bundler = "esbuild"                # Voltemos ao esbuild, que é o padrão moderno

  # MUITO IMPORTANTE: Especifica a pasta node_modules dentro do diretório da função
  # Certifique-se de que o caminho está correto em relação à raiz do seu repositório.
  included_files = [
    "netlify/functions/node_modules/**"
  ]
  # A linha external_node_modules NÃO deve estar presente aqui, pois queremos que elas sejam empacotadas.