# netlify.toml
[build]
  command = "npm install && npm run build --prefix frontend"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
  # Esta linha é a tentativa mais recente para resolver o erro ENOENT do pdf-parse.
  # Ela informa ao esbuild para não empacotar pdfjs-dist diretamente, mas sim tratá-lo como externo.
  external_node_modules = ["pdfjs-dist"] 

  # A linha included_files geralmente não é necessária se o npm install na raiz
  # já instala as dependências na pasta das funções via script postinstall (como configuramos).
  # No entanto, se o problema persistir, poderíamos considerar reativá-la com cautela.

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200