# netlify.toml
[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend" # Instala e constrói o frontend
  publish = "frontend/dist"               # Onde o Vite gera os arquivos de build do React

[functions]
  directory = "netlify/functions"         # Onde suas funções Netlify estão localizadas
  node_bundler = "zisi"                   # Usamos "zisi" para melhor empacotamento de dependências
  
  # Esta linha é crucial para garantir que os node_modules da função sejam incluídos
  included_files = ["netlify/functions/node_modules/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"      # Redireciona chamadas /api para suas funções Netlify
  status = 200