# netlify.toml

[build]
  # Comando para construir o frontend
  command = "npm install && npm run build --prefix frontend"
  # Diretório de publicação do frontend
  publish = "frontend/dist"

[functions]
  # Diretório das funções serverless
  directory = "netlify/functions"
  # Empacotador de funções Node.js
  node_bundler = "esbuild"

  # Linha comentada conforme sugestão para permitir que o esbuild externalize módulos.
  # external_node_modules = []

  # Linha comentada conforme sugestão. Avalie a necessidade de descomentar
  # apenas se tiver um setup específico de node_modules dentro de netlify/functions.
  # included_files = ["netlify/functions/node_modules/**"]